let _msg = {
    login: {
        loginFailAlert: "아이디 또는 패스워드가 일치하지 않습니다",
        loginSuspendAlert: "사용 정지된 계정입니다.",
        loginDormantAlert: "휴면 계정입니다.",
        loginWithdrawal: "탈퇴 처리된 계정입니다.",
    },
    common: {
        downloadConfirm: "다운로드 하시겠습니까?",
        docConfirm: "처리 결과를 변경하시겠습니까?",
        SuccessAlert: "처리가 완료되었습니다",
        FailAlert: "처리에 실패했습니다",
        sendConfirm: "발송하시겠습니까?",
        sendSuccessAlert: "발송에 성공하였습니다",
        sendFailAlert: "발송에 실패하였습니다.",
        pageMoveConfirm: "로그인이 필요한 서비스입니다.\n로그인 페이지로 이동하시겠습니까?",
        insertConfirm: "등록하시겠습니까?",
        insertSuccessAlert: "등록이 완료되었습니다.",
        insertFailAlert: "등록에 실패하였습니다.",
        saveConfirm: "저장하시겠습니까?",
        saveSuccessAlert: "저장이 완료되었습니다.",
        saveFailedAlert: "저장에 실패했습니다!",
        updateSuccessAlert: "수정이 완료되었습니다.",
        updateFailAlert: "수정에 실패하였습니다.",
        deleteConfirm: "삭제하시겠습니까?",
        deleteSuccessAlert: "삭제가 완료되었습니다.",
        deleteFailAlert: "삭제에 실패하였습니다.",
        warningAlert: "경고!",
        cautionAlert: "주의하세요!",
        errorOccurredAlert: "에러가 발생했습니다.",
        pleaseConfirmAlert: "확인하세요!",
        continueOperationAlert: "경고: 이 작업을 계속하시겠습니까?",
        invalidInputAlert: "잘못된 입력입니다",
        unsavedChangesAlert: "저장되지 않은 변경 사항이 있습니다.",
        connectionErrorAlert: "연결 오류!",
        networkIssueAlert: "네트워크 문제 발생!",
        fileNotFoundAlert: "파일을 찾을 수 없습니다.",
        noPermissionAlert: "권한이 없습니다",
        systemErrorAlert: "시스템 오류 발생!",
        internetDisconnectedAlert: "인터넷 연결이 끊겼습니다",
        databaseErrorAlert: "데이터베이스 오류",
        incorrectPasswordAlert: "잘못된 비밀번호입니다.",
        overwriteFileAlert: "파일이 이미 존재합니다. \n덮어쓰시겠습니까?",
        fillEmptyFieldsAlert: "빈 필드를 채워주세요!",
        invalidInputFormatAlert: "입력 형식이 올바르지 않습니다!",
        unknownErrorAlert: "알 수 없는 오류가 발생했습니다.",
        invalidOperationAlert: "잘못된 작업입니다",
        unableLoadImageAlert: "이미지를 불러올 수 없습니다.",
        invalidFileFormatAlert: "파일 형식이 올바르지 않습니다!",
        invalidURLAlert: "잘못된 URL입니다",
        invalidDataFormatAlert: "잘못된 데이터 포맷입니다.",
        unableCompleteOperationAlert: "작업을 완료할 수 없습니다.",
        systemFailureAlert: "시스템 장애 발생!",
        fileSizeTooLargeAlert: "파일 크기가 너무 큽니다!",
        insufficientStorageAlert: "저장 공간이 부족합니다!",
        abnormalBehaviorDetectedAlert: "비정상적인 동작이 감지되었습니다!",
        contactAdministratorAlert: "관리자에게 문의하세요!",
        operationStoppedAlert: "실행 중지!",
        serviceUnavailableAlert: "서비스를 사용할 수 없습니다.",
        tryAgainErrorAlert: "오류! 다시 시도하세요.",
        unableOpenFileAlert: "파일을 열 수 없습니다.",
        pageNotFoundAlert: "해당 페이지를 찾을 수 없습니다.",
        invalidInputFormatAlert: "잘못된 입력 형식!",
        operationCancelledAlert: "작업이 취소되었습니다.",
        unableDeleteFileAlert: "파일을 삭제할 수 없습니다.",
        unauthorizedOperationAlert: "권한이 없는 작업입니다.",
        dataLossOccurredAlert: "데이터 손실이 발생했습니다!",
        operationNotSupportedAlert: "이 작업은 현재 지원되지 않습니다.",
        invalidAuthenticationInfoAlert: "잘못된 인증 정보!",
        abnormalSituationOccurredAlert: "비정상적인 상황이 발생했습니다!",
        invalidRequestAlert: "잘못된 요청!",
        authenticationErrorAlert: "인증 오류!",
        unableDownloadFileAlert: "파일을 다운로드할 수 없습니다.",
        sessionExpiredAlert: "세션이 만료되었습니다",
        accessDeniedAlert: "접근이 거부되었습니다!",
        invalidOperationAlert: "잘못된 조작!",
        unstableNetworkConnectionAlert: "네트워크 연결이 불안정합니다!",
        pleaseTryAgainAlert: "다시 시도하세요!",
        unableUploadFileAlert: "파일을 업로드할 수 없습니다.",
        requestTimeoutAlert: "요청 시간 초과!",
        unableLoadDataAlert: "데이터를 불러올 수 없습니다.",
        invalidFileFormatAlert: "잘못된 파일 형식!",
        connectionDisconnectedAlert: "연결이 중단되었습니다!",
        dataTransmissionErrorAlert: "데이터 전송 오류!",
        unknownErrorTryAgainAlert: "알 수 없는 오류가 발생했습니다. \n다시 시도하세요.",
        abnormalBehaviorDetectedAlert: "비정상적인 행동이 탐지되었습니다!",
        invalidURLFormatAlert: "잘못된 URL 형식!",
        contactSystemAdministratorAlert: "시스템 관리자에게 문의하세요!",
        dataProcessingErrorAlert: "데이터 처리 오류!",
        unknownErrorRefreshPageAlert: "알 수 없는 오류가 발생했습니다. \n페이지를 새로고침하세요.",
        sessionErrorAlert: "세션 오류!",
        databaseConnectionErrorAlert: "데이터베이스 연결 오류!",
        unableLoadImageTryAgainAlert: "이미지를 불러올 수 없습니다. \n다시 시도하세요.",
        UnableFindFileContactAdminAlert: "파일을 찾을 수 없습니다. \n관리자에게 문의하세요.",
        networkErrorCheckConnectionAlert: "네트워크 오류! \n연결을 확인하세요.",
        invalidUserInputAlert: "잘못된 사용자 입력!",
        unauthorizedRequestAlert: "인증되지 않은 요청!",
        invalidFilePathAlert: "잘못된 파일 경로!",
        requestFailedTryAgainAlert: "요청이 실패했습니다. \n다시 시도하세요.",
        dataCorruptedAlert: "데이터가 손상되었습니다!",
        invalidOperationAlert: "올바른 작업이 아닙니다!",
        fileExistsSaveWithDiffNameAlert: "이미 존재하는 파일입니다. \n다른 이름으로 저장하세요.",
        dataTransmissionIssueAlert: "데이터 전송 중 문제가 발생했습니다!",
        InvalidReqContactAdminAlert: "잘못된 요청입니다. \n관리자에게 문의하세요.",
        unableSaveDataAlert: "데이터를 저장할 수 없습니다!",
        unableModifyFileAlert: "파일을 수정할 수 없습니다.",
        unauthorizedAccessAlert: "인증되지 않은 접근입니다!",
        unableUploadImageAlert: "이미지를 업로드할 수 없습니다!",
        potentialDataLossContinueAlert: "데이터 손실이 발생할 수 있습니다. \n계속하시겠습니까?",
        unableSaveImageAlert: "이미지를 저장할 수 없습니다!",
        unableCopyFileAlert: "파일을 복사할 수 없습니다!",
        unableExecuteOperationAlert: "작업을 실행할 수 없습니다!",
        unableDeleteDataAlert: "데이터를 삭제할 수 없습니다",
        invalidAuthenticationTokenAlert: "잘못된 인증 토큰입니다",
        unauthorizedRequestAlert: "권한이 없는 요청입니다!",
        unableLoadPageAlert: "페이지를 로드할 수 없습니다!",
        unableProcessRequestAlert: "요청을 처리할 수 없습니다!",
        sessionExpiredLoginAgainAlert: "세션이 만료되었습니다. \n다시 로그인하세요.",
        unableMoveFileAlert: "파일을 이동할 수 없습니다!",
        unableDownloadImageAlert: "이미지를 다운로드할 수 없습니다!",
        unableDeleteImageAlert: "이미지를 삭제할 수 없습니다!",
        UnauthorizedDiffAcctAlert: "권한이 없습니다. \n다른 계정으로 로그인하세요!",
        abnormalAccessDetectedAlert: "비정상적인 접근입니다!",
        invalidRequestTryAgainAlert: "잘못된 요청입니다. \n다시 시도하세요.",
        invalidAuthenticationInfoAlert: "인증 정보가 잘못되었습니다!",
        unableUpdateDataAlert: "데이터를 업데이트할 수 없습니다!",
        connectionTimeoutAlert: "연결 시간이 초과되었습니다!",
        networkDisconnectedTryAgainAlert: "네트워크 연결이 끊겼습니다. \n다시 시도하세요.",
        unableDeleteFileTryAgainAlert: "파일을 삭제할 수 없습니다. \n다시 시도하세요.",
        unableDeleteImageTryAgainAlert: "이미지를 삭제할 수 없습니다. \n다시 시도하세요.",
        invalidAuthenticationInfoTryAgainAlert: "잘못된 인증 정보입니다. \n다시 시도하세요.",
        unableUploadImageTryAgainAlert: "이미지를 업로드할 수 없습니다. \n다시 시도하세요.",
        potentialDataLossContinueConfirmAlert: "데이터 손실이 발생할 수 있습니다. \n계속하시겠습니까?",
        unableCopyFileTryAgainAlert: "파일을 복사할 수 없습니다. \n다시 시도하세요.",
        invalidRequestContactSupportAlert: "잘못된 요청입니다. \n지원팀에 문의하세요.",
        SessExpLoginAgainAlert: "세션 만료! \n다시 로그인하세요.",
        updateFailedTryAgainAlert: "업데이트에 실패했습니다. \n다시 시도하세요.",
        unableMoveFileTryAgainAlert: "파일을 이동할 수 없습니다. \n다시 시도하세요.",
        DBErrorContactAdminAlert: "데이터베이스 오류 발생! \n관리자에게 문의하세요.",
    },
    approval: {
        insertConfirm: "기안을 등록하시겠습니까?",
        insertSuccessAlert: "기안이 성공적으로 상신되었습니다.",
        insertFailAlert: "기안 상신이 실패하였습니다.",
        insertCancelAlert: "기안 상신을 취소하였습니다.",
        approvalConfirm: "결재 하시겠습니까?",
        approvalSuccessAlert: "결재 승인이 완료되었습니다",
        approvalFailAlert: "결재 승인이 실패하였습니다.",
        returnConfirm: "회수 하시겠습니까?",
        returnConfirmFailAlert: "회수를 취소하였습니다.",
        returnSuccessAlert: "회수가 완료되었습니다.",
        returnFailAlert: "이미 결재 진행중이며, 회수에 실패하였습니다.",
        refuseConfirm: "반려 하시겠습니까?",
        refuseSuccessAlert: "반려가 완료되었습니다.",
        refuseFailAlert: "반려에 실패하였습니다.",
        tempConfirm: "임시저장 하시겠습니까?",
        tempSuccessAlert: "임시저장이 완료되었습니다",
        tempFailAlert: "임시저장에 실패하였습니다",
        tempCancelAlert: "임시저장을 취소하였습니다",
        tempEmptyAlert: "임시 저장할 항목이 없습니다. 항목을 작성해주세요.",
        fillEmptyFieldsAlert: "변경할 즐겨찾기명을 입력해주세요.",
        errorCheckApvLineOrderAlert: "결재 라인 순서를 변경하세요.\n기안 > 검토 > 결재",
        errorCheckApvLine1Alert: "기안자가 누락되었습니다.",
        errorCheckApvLine3Alert: "결재자가 누락되었습니다.",
        errorCheckApvLineEmptyAlert: "결재라인을 선택하세요.",
        errorCheckApvLineExistNoSeCdAlert: "결재구분을 선택하세요.",
        errorCheckAlert1: "작성자는 기안만 선택할 수 있습니다.",
        noSignAlert: "서명하지 않았습니다. 서명해주세요.",
        noChoiceAlert: "양식을 선택해주세요.",
        apvLineConfirm: "해당 결재라인을 사용하시겠습니까?",
        apvReferConfirm: "해당 참조인을 선택하시겠습니까?",
    },
    reservation: {
        scheduleTitleAlert: "일정명이 입력되지 않았습니다.",
        formDateEmptyAlert: "예약일자가 입력되지 않았습니다.",
        formSDateEmptyAlert: "시작 일자가 입력되지 않았습니다.",
        formEDateEmptyAlert: "종료 일자가 입력되지 않았습니다.",
        formDateErrorAlert: "종료 일자는 시작 일자 이후여야 합니다.",
        formTimeErrorAlert: "종료 시간은 시작 시간 이후여야 합니다.",
        formContEmptyAlert: "사용목적이 입력되지 않았습니다.",
        insertSuccessAlert: "예약이 완료되었습니다.",
        insertFailAlert: "예약을 실패했습니다.",
        updateSuccessAlert: "예약이 수정되었습니다.",
        updateFailAlert: "예약 수정에 실패했습니다.",
        deleteConfirm: "예약을 취소하시겠습니까?",
        deleteSuccessAlert: "예약이 취소되었습니다.",
        deleteFailAlert: "예약 취소를 실패했습니다.",
        returnConfirm: "반납하시겠습니까?",
        returnSuccessAlert: "반납 신청이 완료되었습니다.",
        returnFailAlert: "반납 신청에 실패했습니다.",
        adminReturnConfirm: "반납 처리 하시겠습니까?",
        adminReturnSuccessAlert: "반납 처리가 완료되었습니다.",
        adminReturnFailAlert: "반납 처리를 실패했습니다.",
    },
    vacation: {
        deleteConfirm: "휴가를 취소하시겠습니까?",
        deleteSuccessAlert: "휴가가 취소되었습니다.",
        deleteFailAlert: "휴가 취소를 실패했습니다.",
    },
    email: {
        selectNull: "삭제할 메일을 선택하세요.",
        deleteBox: "휴지통으로 이동했습니다.",
    },
    employee: {
        successAlert: "성공적으로 처리되었습니다",
        uploadSuccessAlert: "성공적으로 업로드되었습니다",
    },
};
